version: "{build}"

branches:
  only:
    - master

environment:
  SF_CI_BREW_INSTALL: minimal
  SF_LOG_BOOTSTRAP: "true"
  WSLENV: SF_CI_BREW_INSTALL:SF_LOG_BOOTSTRAP

image: Visual Studio 2019
platform: Any CPU

init:
  - git config --global core.autocrlf input

install:
  - git submodule sync --recursive
  - git submodule update --init --recursive
  - wsl bash -c "cat /etc/os-release"
  - wsl bash -c "./.ci.sh before_install"
  - wsl bash -c "./.ci.sh install"

# before_build:
build_script:
  - wsl bash -c "./.ci.sh before_script"
  - wsl bash -c "./.ci.sh script"
# after_build:

# before_test:
# test_script:
# after_test:

on_success:
  - wsl bash -c "./.ci.sh after_success"
on_failure:
  - wsl bash -c "./.ci.sh after_failure"
on_finish:
  - wsl bash -c "./.ci.sh after_script"

# before_deploy:
# deply_script:
# after_deploy:
